apiVersion: 1

datasources:
  - name: iDT4GDC Postgres
    uid: postgres-ops
    type: postgres
    access: proxy
    url: postgres:5432
    user: grafana
    secureJsonData:
      password: grafana
    jsonData:
      database: opsdemo
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
      maxOpenConns: 20
      maxIdleConns: 5
      connMaxLifetime: 14400

